--liquibase formatted sql

--changeset maslynem:1
CREATE TABLE company
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE customer
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255),
    email      VARCHAR(255),
    age        INTEGER,
    company_id BIGINT REFERENCES company (id) NOT NULL
);


--changeset maslynem:2

INSERT INTO company(name)
VALUES ('IvanCorp'),
       ('MariyaCorp'),
       ('SergeyCorp'),
       ('NikitaCorp');

INSERT INTO customer(name, email, age, company_id)
VALUES ('Ivan', 'ivan@mail.ru', 18, 1),
       ('Anton', 'anton@mail.ru', 19, 1),
       ('Gleb', 'gleb@mail.ru', 20, 1),
       ('Mariya', 'mariya@mail.ru', 21, 2),
       ('Victoria', 'victoria@mail.ru', 22, 2),
       ('Sergey', 'sergey@mail.ru', 23, 3),
       ('Nikita', 'nikita@mail.ru', 24, 4);