server:
  port: ${SERVER_PORT:443}
  ssl:
    key-store: classpath:self-signed-certificate.jks
    key-store-type: pkcs12
    key-store-password: password
    key-password: password
    key-alias: maslynem

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: always