--liquibase formatted sql

--changeset maslynem:1
CREATE TABLE customer
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name  VARCHAR(255),
    email VARCHAR(255),
    age   INTEGER
);

--changeset maslynem:2
INSERT INTO customer(name, email, age) VALUES
                                           ('Ivan', 'ivan@mail.ru', 18),
                                           ('Anton', 'anton@mail.ru', 19),
                                           ('Gleb', 'gleb@mail.ru', 20),
                                           ('Mariya', 'mariya@mail.ru', 21),
                                           ('Victoria', 'victoria@mail.ru', 22),
                                           ('Sergey', 'sergey@mail.ru', 23),
                                           ('Nikita', 'nikita@mail.ru', 24)